name:                openapi-generic-cli
version:             0.1.0.0
github:              "Hazelfire/openapi-generic-cli"
license:             BSD3
author:              "Sam Nolan"
maintainer:          "samnolan555@gmail.com"
copyright:           "2021 Sam Nolan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/openapi-generic-cli#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- http-client-tls
- text
- bytestring
- aeson
- openapi3
- yaml
- lens
- json-pointy
- insert-ordered-containers
- directory
- process
- typed-process

library:
  source-dirs: src

executables:
  semantic-scholar-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi-generic-cli

tests:
  semantic-scholar-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi-generic-cli
